from ChromePool import chromepool
a = chromepool()
temp = a.get()
temp.get('http://washingpatrick.cn')
a.release(temp)
temp2 = a.get()
temp3 = a.get()
temp4 = a.get()
print(temp2.session_id,temp3.session_id,temp4.session_id)
temp2.get('http://washingpatrick.cn')
temp3.get('http://washingpatrick.cn')
temp4.get('http://washingpatrick.cn')
a.delete_all()
